#!/bin/sh

CHANGED_FILES=$(git show --pretty="format:" --name-only | grep .js | grep -v json)
FILES_TO_LINT="$(git rev-parse --show-toplevel)/static/src/js/**/**.js"
ESLINT="$(git rev-parse --show-toplevel)/static/node_modules/.bin/eslint"
DO_LINT="$($ESLINT --color $CHANGED_FILES)"

if [[ "$CHANGED_FILES" = "" ]]; then
	printf "\033[32mNo changed JS files. Pushing to remote.\e[0m\n"
  exit 0
fi

PASS=true

printf "Starting ESLint on changed files:\n\n $CHANGED_FILES\n"]

if [ "$DO_LINT" ]
then
	printf "$DO_LINT\n"
	printf "ESLint failed, do you want to push anyway? (y/n)\n"
	read shouldPushAnyway </dev/tty

	if [[ ! $shouldPushAnyway =~ ^[Yy]$ ]]; then
			[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
	fi
else
	printf "\033[32mESLint passed.\e[0m\n"
	exit 0
fi